/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.smalluml.ide.contentassist.antlr.internal.InternalSMallUMLParser;
import org.smalluml.services.SMallUMLGrammarAccess;

public class SMallUMLParser extends AbstractContentAssistParser {

	@Inject
	private SMallUMLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSMallUMLParser createParser() {
		InternalSMallUMLParser result = new InternalSMallUMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getRelationAccess().getAlternatives(), "rule__Relation__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getClassAccess().getGroup_4(), "rule__Class__Group_4__0");
					put(grammarAccess.getClassAccess().getGroup_5(), "rule__Class__Group_5__0");
					put(grammarAccess.getClassAccess().getGroup_5_3(), "rule__Class__Group_5_3__0");
					put(grammarAccess.getClassAccess().getGroup_6(), "rule__Class__Group_6__0");
					put(grammarAccess.getClassAccess().getGroup_6_3(), "rule__Class__Group_6_3__0");
					put(grammarAccess.getClassAccess().getGroup_7(), "rule__Class__Group_7__0");
					put(grammarAccess.getClassAccess().getGroup_7_3(), "rule__Class__Group_7_3__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getMethodAccess().getGroup_4(), "rule__Method__Group_4__0");
					put(grammarAccess.getMethodAccess().getGroup_4_3(), "rule__Method__Group_4_3__0");
					put(grammarAccess.getMethodAccess().getGroup_5(), "rule__Method__Group_5__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getString0Access().getGroup(), "rule__String0__Group__0");
					put(grammarAccess.getIntegerAccess().getGroup(), "rule__Integer__Group__0");
					put(grammarAccess.getBoolAccess().getGroup(), "rule__Bool__Group__0");
					put(grammarAccess.getRealAccess().getGroup(), "rule__Real__Group__0");
					put(grammarAccess.getUnlimitedNaturalAccess().getGroup(), "rule__UnlimitedNatural__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup(), "rule__Enumeration__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup_5(), "rule__Enumeration__Group_5__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getCompositionAccess().getGroup(), "rule__Composition__Group__0");
					put(grammarAccess.getCompositionAccess().getGroup_4(), "rule__Composition__Group_4__0");
					put(grammarAccess.getCompositionAccess().getGroup_5(), "rule__Composition__Group_5__0");
					put(grammarAccess.getCompositionAccess().getGroup_6(), "rule__Composition__Group_6__0");
					put(grammarAccess.getCompositionAccess().getGroup_6_3(), "rule__Composition__Group_6_3__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup_4(), "rule__Reference__Group_4__0");
					put(grammarAccess.getReferenceAccess().getGroup_5(), "rule__Reference__Group_5__0");
					put(grammarAccess.getReferenceAccess().getGroup_6(), "rule__Reference__Group_6__0");
					put(grammarAccess.getReferenceAccess().getGroup_6_3(), "rule__Reference__Group_6_3__0");
					put(grammarAccess.getClassAccess().getNameAssignment_2(), "rule__Class__NameAssignment_2");
					put(grammarAccess.getClassAccess().getSuperAssignment_4_1(), "rule__Class__SuperAssignment_4_1");
					put(grammarAccess.getClassAccess().getMethodAssignment_5_2(), "rule__Class__MethodAssignment_5_2");
					put(grammarAccess.getClassAccess().getMethodAssignment_5_3_1(), "rule__Class__MethodAssignment_5_3_1");
					put(grammarAccess.getClassAccess().getAttributeAssignment_6_2(), "rule__Class__AttributeAssignment_6_2");
					put(grammarAccess.getClassAccess().getAttributeAssignment_6_3_1(), "rule__Class__AttributeAssignment_6_3_1");
					put(grammarAccess.getClassAccess().getRoleAssignment_7_2(), "rule__Class__RoleAssignment_7_2");
					put(grammarAccess.getClassAccess().getRoleAssignment_7_3_1(), "rule__Class__RoleAssignment_7_3_1");
					put(grammarAccess.getMethodAccess().getNameAssignment_2(), "rule__Method__NameAssignment_2");
					put(grammarAccess.getMethodAccess().getParameterAssignment_4_2(), "rule__Method__ParameterAssignment_4_2");
					put(grammarAccess.getMethodAccess().getParameterAssignment_4_3_1(), "rule__Method__ParameterAssignment_4_3_1");
					put(grammarAccess.getMethodAccess().getReturnTypeAssignment_5_1(), "rule__Method__ReturnTypeAssignment_5_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_4(), "rule__Attribute__TypeAssignment_4");
					put(grammarAccess.getRoleAccess().getNameAssignment_1(), "rule__Role__NameAssignment_1");
					put(grammarAccess.getRoleAccess().getRelationAssignment_4(), "rule__Role__RelationAssignment_4");
					put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
					put(grammarAccess.getParameterAccess().getTypeAssignment_4(), "rule__Parameter__TypeAssignment_4");
					put(grammarAccess.getEnumerationAccess().getValueAssignment_4(), "rule__Enumeration__ValueAssignment_4");
					put(grammarAccess.getEnumerationAccess().getValueAssignment_5_1(), "rule__Enumeration__ValueAssignment_5_1");
					put(grammarAccess.getCompositionAccess().getNameAssignment_2(), "rule__Composition__NameAssignment_2");
					put(grammarAccess.getCompositionAccess().getUpperBoundAssignment_4_1(), "rule__Composition__UpperBoundAssignment_4_1");
					put(grammarAccess.getCompositionAccess().getLowerBoundAssignment_5_1(), "rule__Composition__LowerBoundAssignment_5_1");
					put(grammarAccess.getCompositionAccess().getRoleAssignment_6_2(), "rule__Composition__RoleAssignment_6_2");
					put(grammarAccess.getCompositionAccess().getRoleAssignment_6_3_1(), "rule__Composition__RoleAssignment_6_3_1");
					put(grammarAccess.getReferenceAccess().getNameAssignment_2(), "rule__Reference__NameAssignment_2");
					put(grammarAccess.getReferenceAccess().getUpperBoundAssignment_4_1(), "rule__Reference__UpperBoundAssignment_4_1");
					put(grammarAccess.getReferenceAccess().getLowerBoundAssignment_5_1(), "rule__Reference__LowerBoundAssignment_5_1");
					put(grammarAccess.getReferenceAccess().getRoleAssignment_6_2(), "rule__Reference__RoleAssignment_6_2");
					put(grammarAccess.getReferenceAccess().getRoleAssignment_6_3_1(), "rule__Reference__RoleAssignment_6_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalSMallUMLParser typedParser = (InternalSMallUMLParser) parser;
			typedParser.entryRuleClass();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SMallUMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SMallUMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
