/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.smalluml.parser.antlr.internal.InternalSMallUMLParser;
import org.smalluml.services.SMallUMLGrammarAccess;

public class SMallUMLParser extends AbstractAntlrParser {

	@Inject
	private SMallUMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSMallUMLParser createParser(XtextTokenStream stream) {
		return new InternalSMallUMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Class";
	}

	public SMallUMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SMallUMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
