/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SMallUMLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSuperKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSuperAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cSuperClassCrossReference_4_1_0 = (CrossReference)cSuperAssignment_4_1.eContents().get(0);
		private final RuleCall cSuperClassEStringParserRuleCall_4_1_0_1 = (RuleCall)cSuperClassCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cMethodKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cMethodAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cMethodMethodParserRuleCall_5_2_0 = (RuleCall)cMethodAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cMethodAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cMethodMethodParserRuleCall_5_3_1_0 = (RuleCall)cMethodAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAttributeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAttributeAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cAttributeAttributeParserRuleCall_6_2_0 = (RuleCall)cAttributeAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cAttributeAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cAttributeAttributeParserRuleCall_6_3_1_0 = (RuleCall)cAttributeAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRoleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cRoleAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cRoleRoleParserRuleCall_7_2_0 = (RuleCall)cRoleAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cRoleAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cRoleRoleParserRuleCall_7_3_1_0 = (RuleCall)cRoleAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Class:
		//	{Class}
		//	'Class'
		//	name=EString
		//	'{' ('super' super=[Class|EString])? ('method' '{' method+=Method ("," method+=Method)* '}')? ('attribute' '{'
		//	attribute+=Attribute ("," attribute+=Attribute)* '}')? ('role' '{' role+=Role ("," role+=Role)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Class} 'Class' name=EString '{' ('super' super=[Class|EString])? ('method' '{' method+=Method ("," method+=Method)*
		//'}')? ('attribute' '{' attribute+=Attribute ("," attribute+=Attribute)* '}')? ('role' '{' role+=Role ("," role+=Role)*
		//'}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Class}
		public Action getClassAction_0() { return cClassAction_0; }
		
		//'Class'
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('super' super=[Class|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'super'
		public Keyword getSuperKeyword_4_0() { return cSuperKeyword_4_0; }
		
		//super=[Class|EString]
		public Assignment getSuperAssignment_4_1() { return cSuperAssignment_4_1; }
		
		//[Class|EString]
		public CrossReference getSuperClassCrossReference_4_1_0() { return cSuperClassCrossReference_4_1_0; }
		
		//EString
		public RuleCall getSuperClassEStringParserRuleCall_4_1_0_1() { return cSuperClassEStringParserRuleCall_4_1_0_1; }
		
		//('method' '{' method+=Method ("," method+=Method)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'method'
		public Keyword getMethodKeyword_5_0() { return cMethodKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//method+=Method
		public Assignment getMethodAssignment_5_2() { return cMethodAssignment_5_2; }
		
		//Method
		public RuleCall getMethodMethodParserRuleCall_5_2_0() { return cMethodMethodParserRuleCall_5_2_0; }
		
		//("," method+=Method)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//method+=Method
		public Assignment getMethodAssignment_5_3_1() { return cMethodAssignment_5_3_1; }
		
		//Method
		public RuleCall getMethodMethodParserRuleCall_5_3_1_0() { return cMethodMethodParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('attribute' '{' attribute+=Attribute ("," attribute+=Attribute)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'attribute'
		public Keyword getAttributeKeyword_6_0() { return cAttributeKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//attribute+=Attribute
		public Assignment getAttributeAssignment_6_2() { return cAttributeAssignment_6_2; }
		
		//Attribute
		public RuleCall getAttributeAttributeParserRuleCall_6_2_0() { return cAttributeAttributeParserRuleCall_6_2_0; }
		
		//("," attribute+=Attribute)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//attribute+=Attribute
		public Assignment getAttributeAssignment_6_3_1() { return cAttributeAssignment_6_3_1; }
		
		//Attribute
		public RuleCall getAttributeAttributeParserRuleCall_6_3_1_0() { return cAttributeAttributeParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('role' '{' role+=Role ("," role+=Role)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'role'
		public Keyword getRoleKeyword_7_0() { return cRoleKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//role+=Role
		public Assignment getRoleAssignment_7_2() { return cRoleAssignment_7_2; }
		
		//Role
		public RuleCall getRoleRoleParserRuleCall_7_2_0() { return cRoleRoleParserRuleCall_7_2_0; }
		
		//("," role+=Role)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//role+=Role
		public Assignment getRoleAssignment_7_3_1() { return cRoleAssignment_7_3_1; }
		
		//Role
		public RuleCall getRoleRoleParserRuleCall_7_3_1_0() { return cRoleRoleParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cString0ParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntegerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBoolParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cRealParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cUnlimitedNaturalParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cEnumerationParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Type:
		//	String0 | Integer | Bool | Real | UnlimitedNatural | Enumeration;
		@Override public ParserRule getRule() { return rule; }
		
		//String0 | Integer | Bool | Real | UnlimitedNatural | Enumeration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String0
		public RuleCall getString0ParserRuleCall_0() { return cString0ParserRuleCall_0; }
		
		//Integer
		public RuleCall getIntegerParserRuleCall_1() { return cIntegerParserRuleCall_1; }
		
		//Bool
		public RuleCall getBoolParserRuleCall_2() { return cBoolParserRuleCall_2; }
		
		//Real
		public RuleCall getRealParserRuleCall_3() { return cRealParserRuleCall_3; }
		
		//UnlimitedNatural
		public RuleCall getUnlimitedNaturalParserRuleCall_4() { return cUnlimitedNaturalParserRuleCall_4; }
		
		//Enumeration
		public RuleCall getEnumerationParserRuleCall_5() { return cEnumerationParserRuleCall_5; }
	}
	public class RelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Relation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCompositionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cReferenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Relation:
		//	Composition | Reference;
		@Override public ParserRule getRule() { return rule; }
		
		//Composition | Reference
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Composition
		public RuleCall getCompositionParserRuleCall_0() { return cCompositionParserRuleCall_0; }
		
		//Reference
		public RuleCall getReferenceParserRuleCall_1() { return cReferenceParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class MethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Method");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMethodKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cParameterKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cParameterAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cParameterParameterParserRuleCall_4_2_0 = (RuleCall)cParameterAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cParameterAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cParameterParameterParserRuleCall_4_3_1_0 = (RuleCall)cParameterAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReturnTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cReturnTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cReturnTypeTypeParserRuleCall_5_1_0 = (RuleCall)cReturnTypeAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Method:
		//	{Method}
		//	'Method'
		//	name=EString
		//	'{' ('parameter' '{' parameter+=Parameter ("," parameter+=Parameter)* '}')? ('returnType' returnType=Type)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Method} 'Method' name=EString '{' ('parameter' '{' parameter+=Parameter ("," parameter+=Parameter)* '}')? ('returnType'
		//returnType=Type)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Method}
		public Action getMethodAction_0() { return cMethodAction_0; }
		
		//'Method'
		public Keyword getMethodKeyword_1() { return cMethodKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('parameter' '{' parameter+=Parameter ("," parameter+=Parameter)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'parameter'
		public Keyword getParameterKeyword_4_0() { return cParameterKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_4_2() { return cParameterAssignment_4_2; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_4_2_0() { return cParameterParameterParserRuleCall_4_2_0; }
		
		//("," parameter+=Parameter)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_4_3_1() { return cParameterAssignment_4_3_1; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_4_3_1_0() { return cParameterParameterParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('returnType' returnType=Type)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'returnType'
		public Keyword getReturnTypeKeyword_5_0() { return cReturnTypeKeyword_5_0; }
		
		//returnType=Type
		public Assignment getReturnTypeAssignment_5_1() { return cReturnTypeAssignment_5_1; }
		
		//Type
		public RuleCall getReturnTypeTypeParserRuleCall_5_1_0() { return cReturnTypeTypeParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttributeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeTypeParserRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Attribute:
		//	'Attribute'
		//	name=EString
		//	'{'
		//	'type' type=Type
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Attribute' name=EString '{' 'type' type=Type '}'
		public Group getGroup() { return cGroup; }
		
		//'Attribute'
		public Keyword getAttributeKeyword_0() { return cAttributeKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=Type
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_4_0() { return cTypeTypeParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRelationKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRelationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cRelationRelationCrossReference_4_0 = (CrossReference)cRelationAssignment_4.eContents().get(0);
		private final RuleCall cRelationRelationEStringParserRuleCall_4_0_1 = (RuleCall)cRelationRelationCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Role:
		//	'Role'
		//	name=EString
		//	'{'
		//	'relation' relation=[Relation|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Role' name=EString '{' 'relation' relation=[Relation|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Role'
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'relation'
		public Keyword getRelationKeyword_3() { return cRelationKeyword_3; }
		
		//relation=[Relation|EString]
		public Assignment getRelationAssignment_4() { return cRelationAssignment_4; }
		
		//[Relation|EString]
		public CrossReference getRelationRelationCrossReference_4_0() { return cRelationRelationCrossReference_4_0; }
		
		//EString
		public RuleCall getRelationRelationEStringParserRuleCall_4_0_1() { return cRelationRelationEStringParserRuleCall_4_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParameterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeTypeParserRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Parameter:
		//	'Parameter'
		//	name=EString
		//	'{'
		//	'type' type=Type
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Parameter' name=EString '{' 'type' type=Type '}'
		public Group getGroup() { return cGroup; }
		
		//'Parameter'
		public Keyword getParameterKeyword_0() { return cParameterKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=Type
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_4_0() { return cTypeTypeParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.String0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStringAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStringKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//String0 String:
		//	{String}
		//	'String'
		@Override public ParserRule getRule() { return rule; }
		
		//{String} 'String'
		public Group getGroup() { return cGroup; }
		
		//{String}
		public Action getStringAction_0() { return cStringAction_0; }
		
		//'String'
		public Keyword getStringKeyword_1() { return cStringKeyword_1; }
	}
	public class IntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Integer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntegerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntegerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Integer:
		//	{Integer}
		//	'Integer';
		@Override public ParserRule getRule() { return rule; }
		
		//{Integer} 'Integer'
		public Group getGroup() { return cGroup; }
		
		//{Integer}
		public Action getIntegerAction_0() { return cIntegerAction_0; }
		
		//'Integer'
		public Keyword getIntegerKeyword_1() { return cIntegerKeyword_1; }
	}
	public class BoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Bool");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Bool:
		//	{Bool}
		//	'Bool';
		@Override public ParserRule getRule() { return rule; }
		
		//{Bool} 'Bool'
		public Group getGroup() { return cGroup; }
		
		//{Bool}
		public Action getBoolAction_0() { return cBoolAction_0; }
		
		//'Bool'
		public Keyword getBoolKeyword_1() { return cBoolKeyword_1; }
	}
	public class RealElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Real");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRealAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRealKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Real:
		//	{Real}
		//	'Real';
		@Override public ParserRule getRule() { return rule; }
		
		//{Real} 'Real'
		public Group getGroup() { return cGroup; }
		
		//{Real}
		public Action getRealAction_0() { return cRealAction_0; }
		
		//'Real'
		public Keyword getRealKeyword_1() { return cRealKeyword_1; }
	}
	public class UnlimitedNaturalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.UnlimitedNatural");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUnlimitedNaturalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUnlimitedNaturalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//UnlimitedNatural:
		//	{UnlimitedNatural}
		//	'UnlimitedNatural';
		@Override public ParserRule getRule() { return rule; }
		
		//{UnlimitedNatural} 'UnlimitedNatural'
		public Group getGroup() { return cGroup; }
		
		//{UnlimitedNatural}
		public Action getUnlimitedNaturalAction_0() { return cUnlimitedNaturalAction_0; }
		
		//'UnlimitedNatural'
		public Keyword getUnlimitedNaturalKeyword_1() { return cUnlimitedNaturalKeyword_1; }
	}
	public class EnumerationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Enumeration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEnumerationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueString0ParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueString0ParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Enumeration:
		//	'Enumeration'
		//	'{'
		//	'value' '{' value+=String0 ("," value+=String0)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Enumeration' '{' 'value' '{' value+=String0 ("," value+=String0)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Enumeration'
		public Keyword getEnumerationKeyword_0() { return cEnumerationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//value+=String0
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//String0
		public RuleCall getValueString0ParserRuleCall_4_0() { return cValueString0ParserRuleCall_4_0; }
		
		//("," value+=String0)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//value+=String0
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//String0
		public RuleCall getValueString0ParserRuleCall_5_1_0() { return cValueString0ParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class CompositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Composition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCompositionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCompositionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUpperBoundKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUpperBoundAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUpperBoundEIntParserRuleCall_4_1_0 = (RuleCall)cUpperBoundAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLowerBoundKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLowerBoundAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLowerBoundEIntParserRuleCall_5_1_0 = (RuleCall)cLowerBoundAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRoleKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRoleAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cRoleRoleCrossReference_6_2_0 = (CrossReference)cRoleAssignment_6_2.eContents().get(0);
		private final RuleCall cRoleRoleEStringParserRuleCall_6_2_0_1 = (RuleCall)cRoleRoleCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRoleAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cRoleRoleCrossReference_6_3_1_0 = (CrossReference)cRoleAssignment_6_3_1.eContents().get(0);
		private final RuleCall cRoleRoleEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cRoleRoleCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Composition:
		//	{Composition}
		//	'Composition'
		//	name=EString
		//	'{' ('upperBound' upperBound=EInt)? ('lowerBound' lowerBound=EInt)? ('role' '(' role+=[Role|EString] (","
		//	role+=[Role|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Composition} 'Composition' name=EString '{' ('upperBound' upperBound=EInt)? ('lowerBound' lowerBound=EInt)? ('role' '('
		//role+=[Role|EString] ("," role+=[Role|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Composition}
		public Action getCompositionAction_0() { return cCompositionAction_0; }
		
		//'Composition'
		public Keyword getCompositionKeyword_1() { return cCompositionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('upperBound' upperBound=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'upperBound'
		public Keyword getUpperBoundKeyword_4_0() { return cUpperBoundKeyword_4_0; }
		
		//upperBound=EInt
		public Assignment getUpperBoundAssignment_4_1() { return cUpperBoundAssignment_4_1; }
		
		//EInt
		public RuleCall getUpperBoundEIntParserRuleCall_4_1_0() { return cUpperBoundEIntParserRuleCall_4_1_0; }
		
		//('lowerBound' lowerBound=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'lowerBound'
		public Keyword getLowerBoundKeyword_5_0() { return cLowerBoundKeyword_5_0; }
		
		//lowerBound=EInt
		public Assignment getLowerBoundAssignment_5_1() { return cLowerBoundAssignment_5_1; }
		
		//EInt
		public RuleCall getLowerBoundEIntParserRuleCall_5_1_0() { return cLowerBoundEIntParserRuleCall_5_1_0; }
		
		//('role' '(' role+=[Role|EString] ("," role+=[Role|EString])* ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'role'
		public Keyword getRoleKeyword_6_0() { return cRoleKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//role+=[Role|EString]
		public Assignment getRoleAssignment_6_2() { return cRoleAssignment_6_2; }
		
		//[Role|EString]
		public CrossReference getRoleRoleCrossReference_6_2_0() { return cRoleRoleCrossReference_6_2_0; }
		
		//EString
		public RuleCall getRoleRoleEStringParserRuleCall_6_2_0_1() { return cRoleRoleEStringParserRuleCall_6_2_0_1; }
		
		//("," role+=[Role|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//role+=[Role|EString]
		public Assignment getRoleAssignment_6_3_1() { return cRoleAssignment_6_3_1; }
		
		//[Role|EString]
		public CrossReference getRoleRoleCrossReference_6_3_1_0() { return cRoleRoleCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getRoleRoleEStringParserRuleCall_6_3_1_0_1() { return cRoleRoleEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SMallUML.Reference");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReferenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReferenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUpperBoundKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUpperBoundAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUpperBoundEIntParserRuleCall_4_1_0 = (RuleCall)cUpperBoundAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLowerBoundKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLowerBoundAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLowerBoundEIntParserRuleCall_5_1_0 = (RuleCall)cLowerBoundAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRoleKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRoleAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cRoleRoleCrossReference_6_2_0 = (CrossReference)cRoleAssignment_6_2.eContents().get(0);
		private final RuleCall cRoleRoleEStringParserRuleCall_6_2_0_1 = (RuleCall)cRoleRoleCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRoleAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cRoleRoleCrossReference_6_3_1_0 = (CrossReference)cRoleAssignment_6_3_1.eContents().get(0);
		private final RuleCall cRoleRoleEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cRoleRoleCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Reference:
		//	{Reference}
		//	'Reference'
		//	name=EString
		//	'{' ('upperBound' upperBound=EInt)? ('lowerBound' lowerBound=EInt)? ('role' '(' role+=[Role|EString] (","
		//	role+=[Role|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Reference} 'Reference' name=EString '{' ('upperBound' upperBound=EInt)? ('lowerBound' lowerBound=EInt)? ('role' '('
		//role+=[Role|EString] ("," role+=[Role|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Reference}
		public Action getReferenceAction_0() { return cReferenceAction_0; }
		
		//'Reference'
		public Keyword getReferenceKeyword_1() { return cReferenceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('upperBound' upperBound=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'upperBound'
		public Keyword getUpperBoundKeyword_4_0() { return cUpperBoundKeyword_4_0; }
		
		//upperBound=EInt
		public Assignment getUpperBoundAssignment_4_1() { return cUpperBoundAssignment_4_1; }
		
		//EInt
		public RuleCall getUpperBoundEIntParserRuleCall_4_1_0() { return cUpperBoundEIntParserRuleCall_4_1_0; }
		
		//('lowerBound' lowerBound=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'lowerBound'
		public Keyword getLowerBoundKeyword_5_0() { return cLowerBoundKeyword_5_0; }
		
		//lowerBound=EInt
		public Assignment getLowerBoundAssignment_5_1() { return cLowerBoundAssignment_5_1; }
		
		//EInt
		public RuleCall getLowerBoundEIntParserRuleCall_5_1_0() { return cLowerBoundEIntParserRuleCall_5_1_0; }
		
		//('role' '(' role+=[Role|EString] ("," role+=[Role|EString])* ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'role'
		public Keyword getRoleKeyword_6_0() { return cRoleKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//role+=[Role|EString]
		public Assignment getRoleAssignment_6_2() { return cRoleAssignment_6_2; }
		
		//[Role|EString]
		public CrossReference getRoleRoleCrossReference_6_2_0() { return cRoleRoleCrossReference_6_2_0; }
		
		//EString
		public RuleCall getRoleRoleEStringParserRuleCall_6_2_0_1() { return cRoleRoleEStringParserRuleCall_6_2_0_1; }
		
		//("," role+=[Role|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//role+=[Role|EString]
		public Assignment getRoleAssignment_6_3_1() { return cRoleAssignment_6_3_1; }
		
		//[Role|EString]
		public CrossReference getRoleRoleCrossReference_6_3_1_0() { return cRoleRoleCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getRoleRoleEStringParserRuleCall_6_3_1_0_1() { return cRoleRoleEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private final ClassElements pClass;
	private final TypeElements pType;
	private final RelationElements pRelation;
	private final EStringElements pEString;
	private final MethodElements pMethod;
	private final AttributeElements pAttribute;
	private final RoleElements pRole;
	private final ParameterElements pParameter;
	private final String0Elements pString0;
	private final IntegerElements pInteger;
	private final BoolElements pBool;
	private final RealElements pReal;
	private final UnlimitedNaturalElements pUnlimitedNatural;
	private final EnumerationElements pEnumeration;
	private final EIntElements pEInt;
	private final CompositionElements pComposition;
	private final ReferenceElements pReference;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SMallUMLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pClass = new ClassElements();
		this.pType = new TypeElements();
		this.pRelation = new RelationElements();
		this.pEString = new EStringElements();
		this.pMethod = new MethodElements();
		this.pAttribute = new AttributeElements();
		this.pRole = new RoleElements();
		this.pParameter = new ParameterElements();
		this.pString0 = new String0Elements();
		this.pInteger = new IntegerElements();
		this.pBool = new BoolElements();
		this.pReal = new RealElements();
		this.pUnlimitedNatural = new UnlimitedNaturalElements();
		this.pEnumeration = new EnumerationElements();
		this.pEInt = new EIntElements();
		this.pComposition = new CompositionElements();
		this.pReference = new ReferenceElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.smalluml.SMallUML".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Class:
	//	{Class}
	//	'Class'
	//	name=EString
	//	'{' ('super' super=[Class|EString])? ('method' '{' method+=Method ("," method+=Method)* '}')? ('attribute' '{'
	//	attribute+=Attribute ("," attribute+=Attribute)* '}')? ('role' '{' role+=Role ("," role+=Role)* '}')?
	//	'}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//Type:
	//	String0 | Integer | Bool | Real | UnlimitedNatural | Enumeration;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Relation:
	//	Composition | Reference;
	public RelationElements getRelationAccess() {
		return pRelation;
	}
	
	public ParserRule getRelationRule() {
		return getRelationAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Method:
	//	{Method}
	//	'Method'
	//	name=EString
	//	'{' ('parameter' '{' parameter+=Parameter ("," parameter+=Parameter)* '}')? ('returnType' returnType=Type)?
	//	'}';
	public MethodElements getMethodAccess() {
		return pMethod;
	}
	
	public ParserRule getMethodRule() {
		return getMethodAccess().getRule();
	}
	
	//Attribute:
	//	'Attribute'
	//	name=EString
	//	'{'
	//	'type' type=Type
	//	'}';
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//Role:
	//	'Role'
	//	name=EString
	//	'{'
	//	'relation' relation=[Relation|EString]
	//	'}';
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//Parameter:
	//	'Parameter'
	//	name=EString
	//	'{'
	//	'type' type=Type
	//	'}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//String0 String:
	//	{String}
	//	'String'
	public String0Elements getString0Access() {
		return pString0;
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}
	
	//Integer:
	//	{Integer}
	//	'Integer';
	public IntegerElements getIntegerAccess() {
		return pInteger;
	}
	
	public ParserRule getIntegerRule() {
		return getIntegerAccess().getRule();
	}
	
	//Bool:
	//	{Bool}
	//	'Bool';
	public BoolElements getBoolAccess() {
		return pBool;
	}
	
	public ParserRule getBoolRule() {
		return getBoolAccess().getRule();
	}
	
	//Real:
	//	{Real}
	//	'Real';
	public RealElements getRealAccess() {
		return pReal;
	}
	
	public ParserRule getRealRule() {
		return getRealAccess().getRule();
	}
	
	//UnlimitedNatural:
	//	{UnlimitedNatural}
	//	'UnlimitedNatural';
	public UnlimitedNaturalElements getUnlimitedNaturalAccess() {
		return pUnlimitedNatural;
	}
	
	public ParserRule getUnlimitedNaturalRule() {
		return getUnlimitedNaturalAccess().getRule();
	}
	
	//Enumeration:
	//	'Enumeration'
	//	'{'
	//	'value' '{' value+=String0 ("," value+=String0)* '}'
	//	'}';
	public EnumerationElements getEnumerationAccess() {
		return pEnumeration;
	}
	
	public ParserRule getEnumerationRule() {
		return getEnumerationAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Composition:
	//	{Composition}
	//	'Composition'
	//	name=EString
	//	'{' ('upperBound' upperBound=EInt)? ('lowerBound' lowerBound=EInt)? ('role' '(' role+=[Role|EString] (","
	//	role+=[Role|EString])* ')')?
	//	'}';
	public CompositionElements getCompositionAccess() {
		return pComposition;
	}
	
	public ParserRule getCompositionRule() {
		return getCompositionAccess().getRule();
	}
	
	//Reference:
	//	{Reference}
	//	'Reference'
	//	name=EString
	//	'{' ('upperBound' upperBound=EInt)? ('lowerBound' lowerBound=EInt)? ('role' '(' role+=[Role|EString] (","
	//	role+=[Role|EString])* ')')?
	//	'}';
	public ReferenceElements getReferenceAccess() {
		return pReference;
	}
	
	public ParserRule getReferenceRule() {
		return getReferenceAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
