/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SmallUmlGrammarAccess extends AbstractGrammarElementFinder {
	
	public class PackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Package");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPackageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cBEGINTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cMemberAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMemberNamedElementParserRuleCall_4_0 = (RuleCall)cMemberAssignment_4.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//Package:
		//	{Package}
		//	'Package'
		//	name=EString
		//	BEGIN
		//	member+=NamedElement*
		//	END;
		@Override public ParserRule getRule() { return rule; }
		
		//{Package} 'Package' name=EString BEGIN member+=NamedElement* END
		public Group getGroup() { return cGroup; }
		
		//{Package}
		public Action getPackageAction_0() { return cPackageAction_0; }
		
		//'Package'
		public Keyword getPackageKeyword_1() { return cPackageKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_3() { return cBEGINTerminalRuleCall_3; }
		
		//member+=NamedElement*
		public Assignment getMemberAssignment_4() { return cMemberAssignment_4; }
		
		//NamedElement
		public RuleCall getMemberNamedElementParserRuleCall_4_0() { return cMemberNamedElementParserRuleCall_4_0; }
		
		//END
		public RuleCall getENDTerminalRuleCall_5() { return cENDTerminalRuleCall_5; }
	}
	public class NamedElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.NamedElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cClassParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAttributeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMethodParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cParameterParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRoleParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cCompositionParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cReferenceParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cPackageParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//NamedElement:
		//	Class | Attribute | Method | Parameter | Role | Composition | Reference | Package;
		@Override public ParserRule getRule() { return rule; }
		
		//Class | Attribute | Method | Parameter | Role | Composition | Reference | Package
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Class
		public RuleCall getClassParserRuleCall_0() { return cClassParserRuleCall_0; }
		
		//Attribute
		public RuleCall getAttributeParserRuleCall_1() { return cAttributeParserRuleCall_1; }
		
		//Method
		public RuleCall getMethodParserRuleCall_2() { return cMethodParserRuleCall_2; }
		
		//Parameter
		public RuleCall getParameterParserRuleCall_3() { return cParameterParserRuleCall_3; }
		
		//Role
		public RuleCall getRoleParserRuleCall_4() { return cRoleParserRuleCall_4; }
		
		//Composition
		public RuleCall getCompositionParserRuleCall_5() { return cCompositionParserRuleCall_5; }
		
		//Reference
		public RuleCall getReferenceParserRuleCall_6() { return cReferenceParserRuleCall_6; }
		
		//Package
		public RuleCall getPackageParserRuleCall_7() { return cPackageParserRuleCall_7; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cString0ParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntegerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBoolParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cRealParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cUnlimitedNaturalParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cEnumerationParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Type:
		//	String0 | Integer | Bool | Real | UnlimitedNatural | Enumeration;
		@Override public ParserRule getRule() { return rule; }
		
		//String0 | Integer | Bool | Real | UnlimitedNatural | Enumeration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String0
		public RuleCall getString0ParserRuleCall_0() { return cString0ParserRuleCall_0; }
		
		//Integer
		public RuleCall getIntegerParserRuleCall_1() { return cIntegerParserRuleCall_1; }
		
		//Bool
		public RuleCall getBoolParserRuleCall_2() { return cBoolParserRuleCall_2; }
		
		//Real
		public RuleCall getRealParserRuleCall_3() { return cRealParserRuleCall_3; }
		
		//UnlimitedNatural
		public RuleCall getUnlimitedNaturalParserRuleCall_4() { return cUnlimitedNaturalParserRuleCall_4; }
		
		//Enumeration
		public RuleCall getEnumerationParserRuleCall_5() { return cEnumerationParserRuleCall_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cExtendsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSuperAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cSuperClassCrossReference_3_1_0 = (CrossReference)cSuperAssignment_3_1.eContents().get(0);
		private final RuleCall cSuperClassEStringParserRuleCall_3_1_0_1 = (RuleCall)cSuperClassCrossReference_3_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final RuleCall cBEGINTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Assignment cMethodAssignment_6_0 = (Assignment)cAlternatives_6.eContents().get(0);
		private final RuleCall cMethodMethodParserRuleCall_6_0_0 = (RuleCall)cMethodAssignment_6_0.eContents().get(0);
		private final Assignment cAttributeAssignment_6_1 = (Assignment)cAlternatives_6.eContents().get(1);
		private final RuleCall cAttributeAttributeParserRuleCall_6_1_0 = (RuleCall)cAttributeAssignment_6_1.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Class:
		//	{Class}
		//	'Class'
		//	name=EString ('extends' super=[Class|EString])?
		//	'{'
		//	BEGIN? (method+=Method | attribute+=Attribute)*
		//	END?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Class} 'Class' name=EString ('extends' super=[Class|EString])? '{' BEGIN? (method+=Method | attribute+=Attribute)* END?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Class}
		public Action getClassAction_0() { return cClassAction_0; }
		
		//'Class'
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//('extends' super=[Class|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'extends'
		public Keyword getExtendsKeyword_3_0() { return cExtendsKeyword_3_0; }
		
		//super=[Class|EString]
		public Assignment getSuperAssignment_3_1() { return cSuperAssignment_3_1; }
		
		//[Class|EString]
		public CrossReference getSuperClassCrossReference_3_1_0() { return cSuperClassCrossReference_3_1_0; }
		
		//EString
		public RuleCall getSuperClassEStringParserRuleCall_3_1_0_1() { return cSuperClassEStringParserRuleCall_3_1_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//BEGIN?
		public RuleCall getBEGINTerminalRuleCall_5() { return cBEGINTerminalRuleCall_5; }
		
		//(method+=Method | attribute+=Attribute)*
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//method+=Method
		public Assignment getMethodAssignment_6_0() { return cMethodAssignment_6_0; }
		
		//Method
		public RuleCall getMethodMethodParserRuleCall_6_0_0() { return cMethodMethodParserRuleCall_6_0_0; }
		
		//attribute+=Attribute
		public Assignment getAttributeAssignment_6_1() { return cAttributeAssignment_6_1; }
		
		//Attribute
		public RuleCall getAttributeAttributeParserRuleCall_6_1_0() { return cAttributeAttributeParserRuleCall_6_1_0; }
		
		//END?
		public RuleCall getENDTerminalRuleCall_7() { return cENDTerminalRuleCall_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeTypeParserRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		
		//Attribute:
		//	'+' name=EString ':' type=Type;
		@Override public ParserRule getRule() { return rule; }
		
		//'+' name=EString ':' type=Type
		public Group getGroup() { return cGroup; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//type=Type
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_3_0() { return cTypeTypeParserRuleCall_3_0; }
	}
	public class MethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Method");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPlusSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cParameterAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cParameterParameterParserRuleCall_4_0_0 = (RuleCall)cParameterAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cParameterAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cParameterParameterParserRuleCall_4_1_1_0 = (RuleCall)cParameterAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cReturnTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cReturnTypeTypeParserRuleCall_6_1_0 = (RuleCall)cReturnTypeAssignment_6_1.eContents().get(0);
		
		//Method:
		//	{Method}
		//	'+' name=EString '(' (parameter+=Parameter ("," parameter+=Parameter)*)?
		//	')' (':' returnType=Type)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Method} '+' name=EString '(' (parameter+=Parameter ("," parameter+=Parameter)*)? ')' (':' returnType=Type)?
		public Group getGroup() { return cGroup; }
		
		//{Method}
		public Action getMethodAction_0() { return cMethodAction_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1() { return cPlusSignKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//(parameter+=Parameter ("," parameter+=Parameter)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_4_0() { return cParameterAssignment_4_0; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_4_0_0() { return cParameterParameterParserRuleCall_4_0_0; }
		
		//("," parameter+=Parameter)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_4_1_1() { return cParameterAssignment_4_1_1; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_4_1_1_0() { return cParameterParameterParserRuleCall_4_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//(':' returnType=Type)?
		public Group getGroup_6() { return cGroup_6; }
		
		//':'
		public Keyword getColonKeyword_6_0() { return cColonKeyword_6_0; }
		
		//returnType=Type
		public Assignment getReturnTypeAssignment_6_1() { return cReturnTypeAssignment_6_1; }
		
		//Type
		public RuleCall getReturnTypeTypeParserRuleCall_6_1_0() { return cReturnTypeTypeParserRuleCall_6_1_0; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeTypeParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Parameter:
		//	name=EString ':' type=Type;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString ':' type=Type
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=Type
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_2_0() { return cTypeTypeParserRuleCall_2_0; }
	}
	public class CompositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Composition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cSourceRoleCrossReference_2_0 = (CrossReference)cSourceAssignment_2.eContents().get(0);
		private final RuleCall cSourceRoleEStringParserRuleCall_2_0_1 = (RuleCall)cSourceRoleCrossReference_2_0.eContents().get(1);
		private final Keyword cLessThanSignGreaterThanSignHyphenMinusHyphenMinusKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTargetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTargetRoleCrossReference_4_0 = (CrossReference)cTargetAssignment_4.eContents().get(0);
		private final RuleCall cTargetRoleEStringParserRuleCall_4_0_1 = (RuleCall)cTargetRoleCrossReference_4_0.eContents().get(1);
		
		//Composition:
		//	name=EString? ':' source=[Role|EString] '<>--' target=[Role|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString? ':' source=[Role|EString] '<>--' target=[Role|EString]
		public Group getGroup() { return cGroup; }
		
		//name=EString?
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//source=[Role|EString]
		public Assignment getSourceAssignment_2() { return cSourceAssignment_2; }
		
		//[Role|EString]
		public CrossReference getSourceRoleCrossReference_2_0() { return cSourceRoleCrossReference_2_0; }
		
		//EString
		public RuleCall getSourceRoleEStringParserRuleCall_2_0_1() { return cSourceRoleEStringParserRuleCall_2_0_1; }
		
		//'<>--'
		public Keyword getLessThanSignGreaterThanSignHyphenMinusHyphenMinusKeyword_3() { return cLessThanSignGreaterThanSignHyphenMinusHyphenMinusKeyword_3; }
		
		//target=[Role|EString]
		public Assignment getTargetAssignment_4() { return cTargetAssignment_4; }
		
		//[Role|EString]
		public CrossReference getTargetRoleCrossReference_4_0() { return cTargetRoleCrossReference_4_0; }
		
		//EString
		public RuleCall getTargetRoleEStringParserRuleCall_4_0_1() { return cTargetRoleEStringParserRuleCall_4_0_1; }
	}
	public class ReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Reference");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cSourceRoleCrossReference_2_0 = (CrossReference)cSourceAssignment_2.eContents().get(0);
		private final RuleCall cSourceRoleEStringParserRuleCall_2_0_1 = (RuleCall)cSourceRoleCrossReference_2_0.eContents().get(1);
		private final Keyword cHyphenMinusHyphenMinusHyphenMinusGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTargetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTargetRoleCrossReference_4_0 = (CrossReference)cTargetAssignment_4.eContents().get(0);
		private final RuleCall cTargetRoleEStringParserRuleCall_4_0_1 = (RuleCall)cTargetRoleCrossReference_4_0.eContents().get(1);
		
		//Reference:
		//	name=EString? ':' source=[Role|EString] '--->' target=[Role|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString? ':' source=[Role|EString] '--->' target=[Role|EString]
		public Group getGroup() { return cGroup; }
		
		//name=EString?
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//source=[Role|EString]
		public Assignment getSourceAssignment_2() { return cSourceAssignment_2; }
		
		//[Role|EString]
		public CrossReference getSourceRoleCrossReference_2_0() { return cSourceRoleCrossReference_2_0; }
		
		//EString
		public RuleCall getSourceRoleEStringParserRuleCall_2_0_1() { return cSourceRoleEStringParserRuleCall_2_0_1; }
		
		//'--->'
		public Keyword getHyphenMinusHyphenMinusHyphenMinusGreaterThanSignKeyword_3() { return cHyphenMinusHyphenMinusHyphenMinusGreaterThanSignKeyword_3; }
		
		//target=[Role|EString]
		public Assignment getTargetAssignment_4() { return cTargetAssignment_4; }
		
		//[Role|EString]
		public CrossReference getTargetRoleCrossReference_4_0() { return cTargetRoleCrossReference_4_0; }
		
		//EString
		public RuleCall getTargetRoleEStringParserRuleCall_4_0_1() { return cTargetRoleEStringParserRuleCall_4_0_1; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cClassAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cClassClassCrossReference_3_0 = (CrossReference)cClassAssignment_3.eContents().get(0);
		private final RuleCall cClassClassEStringParserRuleCall_3_0_1 = (RuleCall)cClassClassCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cLowerBoundAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cLowerBoundEIntParserRuleCall_4_2_0 = (RuleCall)cLowerBoundAssignment_4_2.eContents().get(0);
		private final Keyword cCommaKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Assignment cUpperBoundAssignment_4_4 = (Assignment)cGroup_4.eContents().get(4);
		private final RuleCall cUpperBoundEIntParserRuleCall_4_4_0 = (RuleCall)cUpperBoundAssignment_4_4.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4_5 = (Keyword)cGroup_4.eContents().get(5);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Role:
		//	{Role} name=EString? '(' class=[Class|EString] (',' '[' lowerBound=EInt ',' upperBound=EInt ']')? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{Role} name=EString? '(' class=[Class|EString] (',' '[' lowerBound=EInt ',' upperBound=EInt ']')? ')'
		public Group getGroup() { return cGroup; }
		
		//{Role}
		public Action getRoleAction_0() { return cRoleAction_0; }
		
		//name=EString?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//class=[Class|EString]
		public Assignment getClassAssignment_3() { return cClassAssignment_3; }
		
		//[Class|EString]
		public CrossReference getClassClassCrossReference_3_0() { return cClassClassCrossReference_3_0; }
		
		//EString
		public RuleCall getClassClassEStringParserRuleCall_3_0_1() { return cClassClassEStringParserRuleCall_3_0_1; }
		
		//(',' '[' lowerBound=EInt ',' upperBound=EInt ']')?
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_4_1() { return cLeftSquareBracketKeyword_4_1; }
		
		//lowerBound=EInt
		public Assignment getLowerBoundAssignment_4_2() { return cLowerBoundAssignment_4_2; }
		
		//EInt
		public RuleCall getLowerBoundEIntParserRuleCall_4_2_0() { return cLowerBoundEIntParserRuleCall_4_2_0; }
		
		//','
		public Keyword getCommaKeyword_4_3() { return cCommaKeyword_4_3; }
		
		//upperBound=EInt
		public Assignment getUpperBoundAssignment_4_4() { return cUpperBoundAssignment_4_4; }
		
		//EInt
		public RuleCall getUpperBoundEIntParserRuleCall_4_4_0() { return cUpperBoundEIntParserRuleCall_4_4_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4_5() { return cRightSquareBracketKeyword_4_5; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.String0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStringAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStringKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//String0 String:
		//	{String}
		//	'String'
		@Override public ParserRule getRule() { return rule; }
		
		//{String} 'String'
		public Group getGroup() { return cGroup; }
		
		//{String}
		public Action getStringAction_0() { return cStringAction_0; }
		
		//'String'
		public Keyword getStringKeyword_1() { return cStringKeyword_1; }
	}
	public class IntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Integer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntegerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntegerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Integer:
		//	{Integer}
		//	'Integer';
		@Override public ParserRule getRule() { return rule; }
		
		//{Integer} 'Integer'
		public Group getGroup() { return cGroup; }
		
		//{Integer}
		public Action getIntegerAction_0() { return cIntegerAction_0; }
		
		//'Integer'
		public Keyword getIntegerKeyword_1() { return cIntegerKeyword_1; }
	}
	public class BoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Bool");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Bool:
		//	{Bool}
		//	'Bool';
		@Override public ParserRule getRule() { return rule; }
		
		//{Bool} 'Bool'
		public Group getGroup() { return cGroup; }
		
		//{Bool}
		public Action getBoolAction_0() { return cBoolAction_0; }
		
		//'Bool'
		public Keyword getBoolKeyword_1() { return cBoolKeyword_1; }
	}
	public class RealElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Real");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRealAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRealKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Real:
		//	{Real}
		//	'Real';
		@Override public ParserRule getRule() { return rule; }
		
		//{Real} 'Real'
		public Group getGroup() { return cGroup; }
		
		//{Real}
		public Action getRealAction_0() { return cRealAction_0; }
		
		//'Real'
		public Keyword getRealKeyword_1() { return cRealKeyword_1; }
	}
	public class UnlimitedNaturalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.UnlimitedNatural");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUnlimitedNaturalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUnlimitedNaturalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//UnlimitedNatural:
		//	{UnlimitedNatural}
		//	'UnlimitedNatural';
		@Override public ParserRule getRule() { return rule; }
		
		//{UnlimitedNatural} 'UnlimitedNatural'
		public Group getGroup() { return cGroup; }
		
		//{UnlimitedNatural}
		public Action getUnlimitedNaturalAction_0() { return cUnlimitedNaturalAction_0; }
		
		//'UnlimitedNatural'
		public Keyword getUnlimitedNaturalKeyword_1() { return cUnlimitedNaturalKeyword_1; }
	}
	public class EnumerationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.Enumeration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEnumerationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueString0ParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueString0ParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Enumeration:
		//	'Enumeration'
		//	'{'
		//	'value' '{' value+=String0 ("," value+=String0)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Enumeration' '{' 'value' '{' value+=String0 ("," value+=String0)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Enumeration'
		public Keyword getEnumerationKeyword_0() { return cEnumerationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//value+=String0
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//String0
		public RuleCall getValueString0ParserRuleCall_4_0() { return cValueString0ParserRuleCall_4_0; }
		
		//("," value+=String0)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//value+=String0
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//String0
		public RuleCall getValueString0ParserRuleCall_5_1_0() { return cValueString0ParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private final PackageElements pPackage;
	private final NamedElementElements pNamedElement;
	private final TypeElements pType;
	private final EStringElements pEString;
	private final ClassElements pClass;
	private final AttributeElements pAttribute;
	private final MethodElements pMethod;
	private final ParameterElements pParameter;
	private final CompositionElements pComposition;
	private final ReferenceElements pReference;
	private final RoleElements pRole;
	private final String0Elements pString0;
	private final IntegerElements pInteger;
	private final BoolElements pBool;
	private final RealElements pReal;
	private final UnlimitedNaturalElements pUnlimitedNatural;
	private final EnumerationElements pEnumeration;
	private final EIntElements pEInt;
	private final TerminalRule tBEGIN;
	private final TerminalRule tEND;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SmallUmlGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPackage = new PackageElements();
		this.pNamedElement = new NamedElementElements();
		this.pType = new TypeElements();
		this.pEString = new EStringElements();
		this.pClass = new ClassElements();
		this.pAttribute = new AttributeElements();
		this.pMethod = new MethodElements();
		this.pParameter = new ParameterElements();
		this.pComposition = new CompositionElements();
		this.pReference = new ReferenceElements();
		this.pRole = new RoleElements();
		this.pString0 = new String0Elements();
		this.pInteger = new IntegerElements();
		this.pBool = new BoolElements();
		this.pReal = new RealElements();
		this.pUnlimitedNatural = new UnlimitedNaturalElements();
		this.pEnumeration = new EnumerationElements();
		this.pEInt = new EIntElements();
		this.tBEGIN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.BEGIN");
		this.tEND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUml.END");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.smalluml.SmallUml".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Package:
	//	{Package}
	//	'Package'
	//	name=EString
	//	BEGIN
	//	member+=NamedElement*
	//	END;
	public PackageElements getPackageAccess() {
		return pPackage;
	}
	
	public ParserRule getPackageRule() {
		return getPackageAccess().getRule();
	}
	
	//NamedElement:
	//	Class | Attribute | Method | Parameter | Role | Composition | Reference | Package;
	public NamedElementElements getNamedElementAccess() {
		return pNamedElement;
	}
	
	public ParserRule getNamedElementRule() {
		return getNamedElementAccess().getRule();
	}
	
	//Type:
	//	String0 | Integer | Bool | Real | UnlimitedNatural | Enumeration;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Class:
	//	{Class}
	//	'Class'
	//	name=EString ('extends' super=[Class|EString])?
	//	'{'
	//	BEGIN? (method+=Method | attribute+=Attribute)*
	//	END?
	//	'}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//Attribute:
	//	'+' name=EString ':' type=Type;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//Method:
	//	{Method}
	//	'+' name=EString '(' (parameter+=Parameter ("," parameter+=Parameter)*)?
	//	')' (':' returnType=Type)?;
	public MethodElements getMethodAccess() {
		return pMethod;
	}
	
	public ParserRule getMethodRule() {
		return getMethodAccess().getRule();
	}
	
	//Parameter:
	//	name=EString ':' type=Type;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Composition:
	//	name=EString? ':' source=[Role|EString] '<>--' target=[Role|EString];
	public CompositionElements getCompositionAccess() {
		return pComposition;
	}
	
	public ParserRule getCompositionRule() {
		return getCompositionAccess().getRule();
	}
	
	//Reference:
	//	name=EString? ':' source=[Role|EString] '--->' target=[Role|EString];
	public ReferenceElements getReferenceAccess() {
		return pReference;
	}
	
	public ParserRule getReferenceRule() {
		return getReferenceAccess().getRule();
	}
	
	//Role:
	//	{Role} name=EString? '(' class=[Class|EString] (',' '[' lowerBound=EInt ',' upperBound=EInt ']')? ')';
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//String0 String:
	//	{String}
	//	'String'
	public String0Elements getString0Access() {
		return pString0;
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}
	
	//Integer:
	//	{Integer}
	//	'Integer';
	public IntegerElements getIntegerAccess() {
		return pInteger;
	}
	
	public ParserRule getIntegerRule() {
		return getIntegerAccess().getRule();
	}
	
	//Bool:
	//	{Bool}
	//	'Bool';
	public BoolElements getBoolAccess() {
		return pBool;
	}
	
	public ParserRule getBoolRule() {
		return getBoolAccess().getRule();
	}
	
	//Real:
	//	{Real}
	//	'Real';
	public RealElements getRealAccess() {
		return pReal;
	}
	
	public ParserRule getRealRule() {
		return getRealAccess().getRule();
	}
	
	//UnlimitedNatural:
	//	{UnlimitedNatural}
	//	'UnlimitedNatural';
	public UnlimitedNaturalElements getUnlimitedNaturalAccess() {
		return pUnlimitedNatural;
	}
	
	public ParserRule getUnlimitedNaturalRule() {
		return getUnlimitedNaturalAccess().getRule();
	}
	
	//Enumeration:
	//	'Enumeration'
	//	'{'
	//	'value' '{' value+=String0 ("," value+=String0)* '}'
	//	'}';
	public EnumerationElements getEnumerationAccess() {
		return pEnumeration;
	}
	
	public ParserRule getEnumerationRule() {
		return getEnumerationAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal BEGIN:
	//	'synthetic:BEGIN';
	public TerminalRule getBEGINRule() {
		return tBEGIN;
	}
	
	//terminal END:
	//	'synthetic:END';
	public TerminalRule getENDRule() {
		return tEND;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
