/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.smalluml.parser.antlr.internal.InternalSmallUmlParser;

public class SmallUmlTokenSource extends AbstractIndentationTokenSource {

	public SmallUmlTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalSmallUmlParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalSmallUmlParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalSmallUmlParser.RULE_END;
	}

}
