/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSMallUMLScopeProvider extends DelegatingScopeProvider {
}
