/**
 * generated by Xtext 2.10.0
 */
package org.smalluml;

import org.smalluml.AbstractSmallUmlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallUmlRuntimeModule extends AbstractSmallUmlRuntimeModule {
}
