/**
 * generated by Xtext 2.10.0
 */
package org.smalluml;

import org.smalluml.SmallUmlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallUmlStandaloneSetup extends SmallUmlStandaloneSetupGenerated {
  public static void doSetup() {
    SmallUmlStandaloneSetup _smallUmlStandaloneSetup = new SmallUmlStandaloneSetup();
    _smallUmlStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
