/**
 * generated by Xtext 2.10.0
 */
package org.smalluml;

import org.smalluml.SMallUMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SMallUMLStandaloneSetup extends SMallUMLStandaloneSetupGenerated {
  public static void doSetup() {
    SMallUMLStandaloneSetup _sMallUMLStandaloneSetup = new SMallUMLStandaloneSetup();
    _sMallUMLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
