/*
 * generated by Xtext 2.10.0
 */
package org.smalluml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SMallUMLStandaloneSetup extends SMallUMLStandaloneSetupGenerated {

	def static void doSetup() {
		new SMallUMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
