/**
 *
 * $Id$
 */
package smalluml.validation;

import org.eclipse.emf.common.util.EList;

import smalluml.Attribute;
import smalluml.Method;
import smalluml.Role;

/**
 * A sample validator interface for {@link smalluml.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateMethod(EList<Method> value);
	boolean validateAttribute(EList<Attribute> value);
	boolean validateSuper(smalluml.Class value);
	boolean validateRole(EList<Role> value);
}
