/**
 *
 * $Id$
 */
package smalluml.validation;

import org.eclipse.emf.common.util.EList;

import smalluml.Relation;

/**
 * A sample validator interface for {@link smalluml.Package}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageValidator {
	boolean validate();

	boolean validateClass(EList<smalluml.Class> value);
	boolean validateRelation(EList<Relation> value);
}
