/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.smalluml.ui.internal.SmallumlActivator;

public class SMallUMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmallumlActivator.getInstance().getInjector("org.smalluml.SMallUML");
	}

}
